# config.yaml
scenary:
  _target_: src.scenary.base.StackCubeScenary
  usd_file_path: "/home/tay/Desktop/Robot/Asset/FastUMI/Franka_env_3.usd"
  src_cube_cfg: {
      name: cube_red,
      position: [0.586757,-0.174030,0.120000],
      orientation: [0.951017,0.000000,0.000000,0.309137],
      prim_path: /World/Cube,
      scale: [0.05, 0.05, 0.05],
      size: 1.0,
      color: [1, 0, 0]
  }
  target_cube_cfg: {
      name: cube_blue,
      position: [0.561296,0.227596,0.120000],
      orientation: [0.951017,0.000000,0.000000,0.309137],
      prim_path: /World/Cube2,
      scale: [0.05, 0.05, 0.05],
      size: 1.0,
      color: [0, 0, 1]
  }

controller:
  _target_: src.controller.base.ROSServiceController
  ros_service_name: sensor_processing
  
sensor:
  _target_: src.sensor.base.Camera
  camera_prim_path: /World/franka/panda_hand/owl/camera
  camera_freq: 20 
  resolution: [640,480]

robot:
  _target_: src.robots.base.BaseRobot
  robot_prim_path: /World/franka
  joints_name: [
     panda_joint1,panda_joint2,panda_joint3,panda_joint4,panda_joint5,panda_joint6,panda_joint7,panda_finger_joint1
  ]
  ee_prim_path: /World/franka/panda_hand/tool_center
  gripper_joint_name: panda_finger_joint1

dataset:
  _target_: src.dataset.base.ACTDataset
  dataset_dir: ./dataset/stack_cube_act_sim
  episode_nums: 1

task:
  _target_: src.task.base.BaseTask
  replay_horizon: -1  # -1 代表 replay 所有数据

sensor_list: []    # 可以加入更多 sensor 配置  